name: 'Dependency Review'
on:
  pull_request:
    branches: [ "prod" ]
    paths:
      - '**/package.json'
      - '**/package-lock.json'
      - '**/yarn.lock'
  push:
    branches: [ "prod" ]
    paths:
      - '**/package.json'
      - '**/package-lock.json'
      - '**/yarn.lock'

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  pull-request-review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Backend Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always
          working-directory: backend
          base-ref: ${{ github.event.pull_request.base.sha }}
          head-ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Frontend Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always
          working-directory: frontend
          base-ref: ${{ github.event.pull_request.base.sha }}
          head-ref: ${{ github.event.pull_request.head.sha }}

  push-audit:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Backend Audit
        working-directory: backend
        run: |
          npm install
          npm audit

      - name: Frontend Audit
        working-directory: frontend
        run: |
          npm install
          npm audit

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects

      # Optional: Submit the results to GitHub's dependency graph
      - name: Upload dependency snapshot
        uses: advanced-security/maven-dependency-submission-action@v3
        with:
          directory: .