name: 'Dependency review'
on:
  pull_request:
    branches: [ "prod" ]
    paths:
      - 'frontend/package.json'
      - 'frontend/package-lock.json'
      - 'frontend/yarn.lock'
      - 'backend/package.json'
      - 'backend/package-lock.json'
      - 'backend/yarn.lock'

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Backend Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always
          working-directory: backend
          base-ref: ${{ github.event.pull_request.base.sha }}
          head-ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Frontend Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always
          working-directory: frontend
          base-ref: ${{ github.event.pull_request.base.sha }}
          head-ref: ${{ github.event.pull_request.head.sha }}

      # Optional: Add vulnerability scanning thresholds
      # You can uncomment and modify these as needed
      # with:
      #   fail-on-severity: moderate
      #   deny-licenses: GPL-1.0-or-later, LGPL-2.0-or-later
      #   retry-on-snapshot-warnings: true