name: 'Security Scan'

on:
  push:
    branches: [ "prod" ]

permissions:
  contents: read
  security-events: write

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Backend Security Check
        working-directory: backend
        run: |
          npm install
          npm audit
          npm outdated || true

      - name: Frontend Security Check
        working-directory: frontend
        run: |
          npm install
          npm audit
          npm outdated || true

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript"