name: 'Security Scan'

on:
  push:
    branches: [ "prod" ]

permissions:
  contents: read
  security-events: write
  actions: read
  issues: write  # Add this permission for creating issues

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:  # Also specify permissions at job level
      contents: read
      security-events: write
      actions: read
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Set up Snyk
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Backend Dependencies Check
        working-directory: backend
        run: |
          npm ci
          snyk test || true
          snyk monitor

      - name: Frontend Dependencies Check
        working-directory: frontend
        run: |
          npm ci
          snyk test || true
          snyk monitor

      - name: Code Analysis
        run: snyk code test --sarif > snyk-code.sarif || true

      - name: Upload Security Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif

      - name: Create Issue on Failure
        if: ${{ failure() }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Explicitly specify token
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Security Vulnerabilities Detected',
              body: 'Security scan found vulnerabilities in the latest push to prod. Please check the action logs.',
              labels: ['security']
            })